/*

Project euler, problem 2: https://www.projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>
using namespace std;

int main()
{
    long sum = 0;

    int p1 = 0;
    int p2 = 1;

    while (true) {
        int phi = p1 + p2;

        if (phi > 4000000) {
            break;
        }
        p1 = p2;
        p2 = phi;
        if (!(phi & 1)) {  // the number is even
            sum += phi;
        }
    }
    cout << sum << endl;
}